// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA70M2G5-lOKUXls-JHIoWGLulIZwcBXKE',
    appId: '1:184365416703:web:b796a5f0e8eb657ee0ccca',
    messagingSenderId: '184365416703',
    projectId: 'recipe-69abc',
    authDomain: 'recipe-69abc.firebaseapp.com',
    storageBucket: 'recipe-69abc.firebasestorage.app',
    measurementId: 'G-XS0N4MNQSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOFYB30HNLraTvjZu9YYVnRI-5IIlbW1I',
    appId: '1:184365416703:android:7fde5e7437d71e4ee0ccca',
    messagingSenderId: '184365416703',
    projectId: 'recipe-69abc',
    storageBucket: 'recipe-69abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYdduAa4DlllU8ehlYGrO50nY7DZ8mSSM',
    appId: '1:184365416703:ios:3bf03c310f12b671e0ccca',
    messagingSenderId: '184365416703',
    projectId: 'recipe-69abc',
    storageBucket: 'recipe-69abc.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYdduAa4DlllU8ehlYGrO50nY7DZ8mSSM',
    appId: '1:184365416703:ios:3bf03c310f12b671e0ccca',
    messagingSenderId: '184365416703',
    projectId: 'recipe-69abc',
    storageBucket: 'recipe-69abc.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA70M2G5-lOKUXls-JHIoWGLulIZwcBXKE',
    appId: '1:184365416703:web:4f0afe77649f367be0ccca',
    messagingSenderId: '184365416703',
    projectId: 'recipe-69abc',
    authDomain: 'recipe-69abc.firebaseapp.com',
    storageBucket: 'recipe-69abc.firebasestorage.app',
    measurementId: 'G-0MV7H9BK31',
  );
}
